#!/usr/bin/env zsh

# Set up the prompt
autoload -Uz promptinit
promptinit

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' group-name ''
eval "$(dircolors -b)"
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Git 
git_branch_color() {
    local message=""
    local message_color="%F{green}"

    local staged=$(git status --porcelain 2>/dev/null | grep -e "^M " -e "^A ")
    local unstaged=$(git status --porcelain 2>/dev/null | grep -e "^ M" -e "^??")

    if [[ -n ${staged} ]]; then
        message_color="%F{yellow}"
    elif [[ -n ${unstaged} ]]; then
        message_color="%F{red}"
    fi

    local branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
    if [[ -n ${branch} ]]; then
        message+="${message_color}${branch}%f"
    fi

    if [ ! -z ${message} ]; then
      echo -n " ${message}%f"
    fi
}

#### CHECKS ####
# Check if antigen is installed. If not, download the script.
if [ ! -f "$HOME/.zsh/antigen.zsh" ]; then
  mkdir -p "$HOME/.zsh"
  curl -L git.io/antigen > "$HOME/.zsh/antigen.zsh"
  clear
fi

# Check if starship is installed. If not, download and install it.
if ! command -v starship &>/dev/null; then
  sh -c "$(curl -fsSL https://starship.rs/install.sh)"
  clear
fi

# Aliases
alias ls="ls --color=auto"
alias la="ls -a --color=auto"
alias ll="ls -l --color=auto"
alias lla="ls -la --color=auto"
alias vim="nvim"
alias v="nvim"
alias sv="sudoedit"
alias _vim="/usr/bin/vim"
alias update="sudo apt update -y; sudo apt upgrade -y; sudo apt autoremove -y"
alias ins="sudo apt install -y"
alias rem="sudo apt autoremove --purge"

GLOBALIAS_FILTER_VALUES=(ls la ll lla)

# Lang
export LANG=en_US.UTF-8

# Colored man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
export LESS=-r

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# Plugins
source "$HOME/.zsh/antigen.zsh"

antigen bundle command-not-found
antigen bundle globalias
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle shrink-path

antigen apply

# Setup prompt
setopt prompt_subst
PROMPT='%F{cyan}$(shrink_path -f)$(git_branch_color) %F{magenta}$%f '
