#!/usr/bin/env zsh

# Set up the prompt
autoload -Uz promptinit
promptinit

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' group-name ''
eval "$(dircolors -b)"
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

#### CHECKS ####
# Check if antigen is installed. If not, download the script.
if [ ! -f "$HOME/.zsh/antigen.zsh" ]; then
  mkdir -p "$HOME/.zsh"
  curl -L git.io/antigen > "$HOME/.zsh/antigen.zsh"
  clear
fi

# Aliases
alias ls="ls --color=auto"
alias la="ls -a --color=auto"
alias ll="ls -l --color=auto"
alias lla="ls -la --color=auto"
alias vim="nvim"
alias _vim="/usr/bin/vim"
alias update="sudo pacman -Fy; sudo pkgfile --update; yay -Syu --sudoloop --noconfirm; antigen update; nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'; echo 'Update completed :)'; sleep 2"
alias ins="sudo pacman -S"
alias rem="sudo pacman -Rns"
alias yins="yay -S"
alias yrem="yay -Rns"

GLOBALIAS_FILTER_VALUES=(ls la ll lla)

# Colored man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
export LESS=-r

# Fix shell
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey  "^[[3~"  delete-char

# Plugins
source "$HOME/.zsh/antigen.zsh"

antigen bundle globalias
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle shrink-path

antigen apply

# Git
autoload -Uz vcs_info
zstyle ':vcs_info:git*' formats "%b "
zstyle ':vcs_info:*' enable git

# Setup prompt
setopt prompt_subst

precmd() {
  vcs_info
  
  PROMPT="%F{cyan}$(shrink_path -f) "

  if [[ -n ${vcs_info_msg_0_} ]]; then
    local gs=$(git status 2>/dev/null)
    local color=''

    if [[ -n ${gs} ]]; then
      if [[ ! $gs =~ "working tree clean" ]]; then
        color="%F{red}"
      elif [[ $gs =~ "Your branch is ahead of" ]]; then
        color="%F{yellow}"
      elif [[ $gs =~ "nothing to commit" ]]; then
        color="%F{green}"
      fi
    fi

    PROMPT+="${color}${vcs_info_msg_0_}"
  fi

  PROMPT+="%F{magenta}$%f "
}
