#!/usr/bin/env bash

# zsh
rm "$HOME/.zshrc" 2>/dev/null
ln -sf "$(pwd)/dot_zshrc" "$HOME/.zshrc"

# if not in WSL environment
if ! grep -q microsoft /proc/version; then
	# alacritty
	rm -rf "$HOME/.config/alacritty" 2>/dev/null
	mkdir -p "$HOME/.config/alacritty"
	ln -sf "$(pwd)/alacritty.yml" "$HOME/.config/alacritty/alacritty.yml"
fi

# tmux
rm "$HOME/.tmux.conf" 2>/dev/null
ln -sf "$(pwd)/dot_tmux.conf" "$HOME/.tmux.conf"

# install TPM
rm -rf "$HOME/.tmux" 2>/dev/null
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
